// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cnqewaajpwejnmsahtqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNucWV3YWFqcHdlam5tc2FodHFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MzAwODYsImV4cCI6MjA2OTAwNjA4Nn0.OODJxLZ88JStvLcuR4jWZqOaSQeGoiCBYnjK9zxoBkY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});